// flow-typed signature: 770dd03dbf89535f31742a1183a2a58d
// flow-typed version: <<STUB>>/react-thunk_v^1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-thunk/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-thunk/dist/es/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-thunk/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-thunk/dist/commonjs/index'>;
}
declare module 'react-thunk/dist/es/index.js' {
  declare module.exports: $Exports<'react-thunk/dist/es/index'>;
}
