export const types = {
    GET_ANIMALS_REQUEST: 'GET_ANIMALS_REQUEST',
    GET_ANIMALS_SUCCESS: 'GET_ANIMALS_SUCCESS',
    GET_ANIMALS_FAILURE: 'GET_ANIMALS_FAILURE',
    UPDATE_ANIMAL_REQUEST: 'UPDATE_ANIMAL_REQUEST',
    UPDATE_ANIMAL_SUCCESS: 'UPDATE_ANIMAL_SUCCESS',
    UPDATE_ANIMAL_FAILURE: 'UPDATE_ANIMAL_FAILURE',
    DELETE_ANIMAL_REQUEST: 'DELETE_ANIMAL_REQUEST',
    DELETE_ANIMAL_SUCCESS: 'DELETE_ANIMAL_SUCCESS',
    DELETE_ANIMAL_FAILURE: 'DELETE_ANIMAL_FAILURE'
};