//@flow

export const actionTypes = {
    ADD_ANIMAL_REQUEST: 'ADD_ANIMAL_REQUEST',
    ADD_ANIMAL_SUCCESS: 'ADD_ANIMAL_SUCCESS',
    ADD_ANIMAL_FAILURE: 'ADD_ANIMAL_FAILURE',
    CHANGE_FIELD_VALUE: 'CHANGE_FIELD_VALUE',
};